### ISSUE TITLE
Installation in High Sierra and 2.5.5

### ISSUE THREAD

**Issue by alduxvm** [TH3Mjuss/Install_pynaoqi_SDK_on_mac_10.11#2]
Hi!

Perhaps this is an old topic, I want to install naoqi 2.5.5 in a High Sierra, the script will not work for this version (due to locations), but I also tried the 2.4.3 version and after doing the installations of the .dylib files, I still cannot do `import qi` or similar in the python console...

Have you tried 2.5.5 in High sierra? or 2.4.3?

Thanks

**Comment by Mehders** [comment]
Hello,

Unfortunately, this script was meant for macOS 10.11 and I am not able to maintain it up to date. 
Feel free to clone the repo in order to make a working script out of it.

Kind regards
